---
- name: Backup f5 Configuration
  hosts: appc_bigip_lb
  gather_facts: false
  connection: local

  vars:
    # ansible_network_os: f5
    f5_provider:
      server: "{{ ansible_host }}"
      user: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      validate_certs: false
      server_port: "{{ f5_access_port }}"
      timeout: "{{ f5_timeout }}"

  pre_tasks:
    - name: Include specific project variables
      ansible.builtin.include_vars:
        dir: group_vars
      delegate_to: localhost

  tasks:
    - name: Collect running configs and write to a temporary file
      ansible.builtin.import_role:
        name: role-f5-config-backup
      vars:
        _backup_: true
        _tmp_root_dir_: "{{ tmp_base_dir }}"
        _provider_: "{{ f5_provider }}"
        _running_config_file_path_: "{{ tmp_base_dir }}/{{ git_repo_config_backup_dir_path }}/{{ config_backup_file_name }}"
        _ucs_file_name_: "{{ f5_ucs_file_name }}"
        _ucs_file_backup_path_: "{{ tmp_base_dir }}/{{ git_repo_config_backup_dir_path }}/{{ f5_ucs_file_name }}"