---
- name: Backup f5 Configuration
  hosts: appc_bigip_lb
  gather_facts: false
  connection: local

  vars:
    # ansible_network_os: f5
    f5_provider:
      server: "{{ ansible_host }}"
      user: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      validate_certs: false
      server_port: "{{ f5_access_port }}"
      timeout: "{{ f5_timeout }}"

  pre_tasks:
    - name: Include specific project variables
      ansible.builtin.include_vars:
        dir: group_vars
      delegate_to: localhost

  tasks:
    - name: "Backup running configs to Gitlab repo => {{ config_backup_git_repo_name }}"
      ansible.builtin.import_role:
        name: role-f5-config-backup
      vars:
        backup: true
        tmp_root_dir: "{{ root_dir }}"
        vendor_dir: "{{ config_backup_git_repo_f5_dir }}"
        provider: "{{ f5_provider }}"
        git_repo_name: "{{ config_backup_git_repo_name }}"
        git_repo_url: "{{ config_backup_git_repo_url }}"
        git_repo_branch: "{{ config_backup_git_repo_branch }}"
        git_user: "{{ git_user }}"
        git_user_email: "{{ git_user_email }}"