---
# UCS file backup
- name: UCS Backup - Remove UCS file left on device
  f5networks.f5_modules.bigip_ucs:
    ucs: "{{ ucs_filename }}"
    state: absent
    provider: "{{ provider }}"
  delegate_to: localhost
  ignore_errors: true

- name: UCS Backup - Create empty file as placeholder on controller
  ansible.builtin.file:
    path: "{{ root_dir }}/{{ ucs_filename }}"
    state: touch
  delegate_to: localhost
  ignore_errors: true

- name: UCS Backup - Download a new UCS 
  f5networks.f5_modules.bigip_ucs_fetch:
    src: "{{ ucs_filename }}"
    dest: "{{ root_dir }}/{{ ucs_filename }}"
    provider: "{{ provider }}"
    async_timeout: 600
  delegate_to: localhost
  ignore_errors: true